server:
  port: 8081

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver